In [5]:
import requests,json
def get_coordinates():
    api_key="8139b2c6a5572a1d374589298e095a5e"
    city=input("Enter City Name:")
    request_url=f"http://api.openweathermap.org/geo/1.0/direct?q={city}&appid={api_key}"
    response=requests.get(request_url)
    coordinates=response.json()
    print(json.dumps(coordinates,indent=5))
    lattitude=coordinates[0]['lat']
    longitude=coordinates[0]['lon']
    return lattitude,longitude,city
lat,lon,city=get_coordinates()
print(city)
print("--------------------------------------")
print("Lattitude:",lat)
print("Longitude:",lon)

Enter City Name: Ahmedabad

[
     {
          "name": "Ahmedabad",
          "local_names": {
               "tt": "\u04d8\u0445\u043c\u04d9\u0442\u0430\u0431\u0430\u0434",
               "mr": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "pl": "Ahmadabad",
               "bn": "\u0986\u09b9\u09ae\u09c7\u09a6\u09be\u09ac\u09be\u09a6",
               "eo": "Ahmadabado",
               "ne": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "feature_name": "Ahmedabad",
               "ml": "\u0d05\u0d39\u0d2e\u0d4d\u0d2e\u0d26\u0d3e\u0d2c\u0d3e\u0d26\u0d4d",
               "ta": "\u0b85\u0b95\u0bae\u0ba4\u0bbe\u0baa\u0bbe\u0ba4\u0bcd",
               "uk": "\u0410\u0445\u043c\u0435\u0434\u0430\u0431\u0430\u0434",
               "ru": "\u0410\u0445\u043c\u0430\u0434\u0430\u0431\u0430\u0434",
               "hi": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "te": "\u0c05\u0c39\u0c4d\u0c2e\u0c26\u0c3e\u0c2c\u0c3e\u0c26\u0c4d",
               "ja": "\u30a2\u30d5\u30de\u30c0\u30fc\u30d0\u30fc\u30c9",
               "pa": "\u0a05\u0a39\u0a3f\u0a2e\u0a26\u0a3e\u0a2c\u0a3e\u0a26",
               "zh": "\u827e\u54c8\u8fc8\u8fbe\u5df4\u5fb7",
               "gu": "\u0a85\u0aae\u0aa6\u0abe\u0ab5\u0abe\u0aa6",
               "de": "Ahmedabad",
               "cs": "Ahmad\u00e1b\u00e1d",
               "kn": "\u0c85\u0cb9\u0ccd\u0cae\u0ca6\u0cbe\u0cac\u0cbe\u0ca6\u0ccd",
               "ascii": "Ahmedabad",
               "en": "Ahmedabad",
               "or": "\u0b05\u0b39\u0b2e\u0b26\u0b3e\u0b2c\u0b3e\u0b26",
               "he": "\u05d0\u05d7\u05de\u05d3\u05d0\u05d1\u05d0\u05d3",
               "ur": "\u0627\u062d\u0645\u062f \u0622\u0628\u0627\u062f",
               "ar": "\u0623\u062d\u0645\u062f \u0622\u0628\u0627\u062f",
               "oc": "Ahmadabad"
          },
          "lat": 23.0215374,
          "lon": 72.5800568,
          "country": "IN",
          "state": "Gujarat"
     }
]
Ahmedabad
--------------------------------------
Lattitude: 23.0215374
Longitude: 72.5800568

In [6]:
import requests,json
def current_weather_data():
    api_key="8139b2c6a5572a1d374589298e095a5e"
    request_url=f"https://api.openweathermap.org/data/2.5/weather?lat={str(lat)}&lon={str(lon)}&appid={api_key}"
    response=requests.get(request_url)
    current_weather=response.json()
    print(json.dumps(current_weather,indent=5))
    description=current_weather["weather"][0]["description"]
    temp=current_weather["main"]["temp"]
    pressure=current_weather["main"]["pressure"]
    humidity=current_weather["main"]["humidity"]
    wind_speed=current_weather["wind"]["speed"]
    visibility=current_weather["visibility"]
    return description,temp,pressure,humidity,wind_speed,visibility
description,temp,pressure,humidity,wind_speed,visibility=current_weather_data()
print("Description:",description)
print("Temprature:",temp)
print("Pressure:",pressure)
print("Humidity:",humidity)
print("WindSpeed",wind_speed)
print("Visibility",visibility)

{
     "coord": {
          "lon": 72.5801,
          "lat": 23.0215
     },
     "weather": [
          {
               "id": 711,
               "main": "Smoke",
               "description": "smoke",
               "icon": "50d"
          }
     ],
     "base": "stations",
     "main": {
          "temp": 309.19,
          "feels_like": 311.69,
          "temp_min": 309.19,
          "temp_max": 309.19,
          "pressure": 1006,
          "humidity": 38,
          "sea_level": 1006,
          "grnd_level": 1001
     },
     "visibility": 4000,
     "wind": {
          "speed": 4.12,
          "deg": 200
     },
     "clouds": {
          "all": 0
     },
     "dt": 1779778325,
     "sys": {
          "type": 1,
          "id": 9049,
          "country": "IN",
          "sunrise": 1779755113,
          "sunset": 1779803309
     },
     "timezone": 19800,
     "id": 1279233,
     "name": "Ahmedabad",
     "cod": 200
}
Description: smoke
Temprature: 309.19
Pressure: 1006
Humidity: 38
WindSpeed 4.12
Visibility 4000

In [16]:
def current_air_pollution():
    api_key="8139b2c6a5572a1d374589298e095a5e"
    request_url=f"http://api.openweathermap.org/data/2.5/air_pollution/forecast?lat={lat}&lon={lon}&appid={api_key}"
    response=requests.get(request_url)
    air_pollution=response.json()
    #print(json.dumps(air_pollution,indent=5))
    aqi=air_pollution['list'][0]['main']['aqi']
    quality_index={1:"Good",2:"Fair",3:"Moderate",4:"Poor",5:"VeryPoor"}
    print("Air Quality Index:",quality_index[aqi])
current_air_pollution()

Air Quality Index: Fair

In [28]:
import pandas as pd
date=[]
description=[]
temp=[]
pressure=[]
humidity=[]
visibility=[]
wind_speed=[]
def forecast():
    api_key="8139b2c6a5572a1d374589298e095a5e"
    request_url=f"https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={api_key}"
    response=requests.get(request_url)
    weather=response.json()
   # print(json.dumps(weather,indent=5))
    for i in weather['list']:
        date.append(i["dt_txt"])
        description.append(i["weather"][0]["description"])
        temp.append(i["main"]["temp"])
        pressure.append(i["main"]["pressure"])
        humidity.append(i["main"]["humidity"])
        visibility.append(i["visibility"])
        wind_speed.append(i["wind"]["speed"])
forecast()
df=pd.DataFrame({"Date_Time":date,"Description":description,"Temprature":temp,"Pressure":pressure,"Humidity":humidity,"Visibility":visibility,"windSpeed":wind_speed})

In [29]:
df

,Date_Time,Description,Temprature,Pressure,Humidity,Visibility,windSpeed
0,2026-05-26 09:00:00,clear sky,310.67,1007,31,10000,4.87
1,2026-05-26 12:00:00,clear sky,313.40,1005,23,10000,5.66
2,2026-05-26 15:00:00,clear sky,308.33,1006,39,10000,5.12
3,2026-05-26 18:00:00,clear sky,305.21,1007,57,10000,2.92
4,2026-05-26 21:00:00,clear sky,303.21,1006,62,10000,3.95
5,2026-05-27 00:00:00,clear sky,302.65,1007,62,10000,4.78
6,2026-05-27 03:00:00,clear sky,305.03,1009,50,10000,5.00
7,2026-05-27 06:00:00,clear sky,311.79,1008,25,10000,5.14
8,2026-05-27 09:00:00,clear sky,316.06,1005,15,10000,5.63
9,2026-05-27 12:00:00,clear sky,316.33,1003,14,10000,6.11
10,2026-05-27 15:00:00,clear sky,306.80,1006,50,10000,5.78
11,2026-05-27 18:00:00,clear sky,305.67,1008,50,10000,2.79
12,2026-05-27 21:00:00,clear sky,302.94,1006,63,10000,4.68
13,2026-05-28 00:00:00,clear sky,302.78,1007,60,10000,5.03
14,2026-05-28 03:00:00,clear sky,304.97,1009,52,10000,5.91
15,2026-05-28 06:00:00,clear sky,312.36,1007,23,10000,6.11
16,2026-05-28 09:00:00,clear sky,317.27,1004,13,10000,6.45
17,2026-05-28 12:00:00,clear sky,317.03,1002,13,10000,6.80
18,2026-05-28 15:00:00,clear sky,307.78,1005,40,10000,4.84
19,2026-05-28 18:00:00,clear sky,304.78,1006,46,10000,4.48
20,2026-05-28 21:00:00,clear sky,304.13,1006,54,10000,5.56
21,2026-05-29 00:00:00,clear sky,302.30,1007,66,10000,5.40
22,2026-05-29 03:00:00,clear sky,304.68,1008,53,10000,7.25
23,2026-05-29 06:00:00,clear sky,311.77,1006,26,10000,7.62
24,2026-05-29 09:00:00,clear sky,315.95,1003,17,10000,8.09
25,2026-05-29 12:00:00,clear sky,315.81,1001,17,10000,7.96
26,2026-05-29 15:00:00,clear sky,307.67,1003,36,10000,8.32
27,2026-05-29 18:00:00,clear sky,305.89,1003,46,10000,5.63
28,2026-05-29 21:00:00,clear sky,303.03,1003,61,10000,6.87
29,2026-05-30 00:00:00,clear sky,301.72,1004,70,10000,6.54
30,2026-05-30 03:00:00,clear sky,304.61,1005,56,10000,7.80
31,2026-05-30 06:00:00,clear sky,311.27,1003,32,10000,8.71
32,2026-05-30 09:00:00,clear sky,315.77,1000,21,10000,8.71
33,2026-05-30 12:00:00,clear sky,314.85,999,22,10000,8.73
34,2026-05-30 15:00:00,clear sky,310.05,1001,34,10000,7.02
35,2026-05-30 18:00:00,clear sky,305.27,1003,53,10000,7.99
36,2026-05-30 21:00:00,clear sky,302.99,1003,67,10000,6.17
37,2026-05-31 00:00:00,clear sky,302.18,1003,71,10000,5.30
38,2026-05-31 03:00:00,broken clouds,304.32,1005,58,10000,6.94
39,2026-05-31 06:00:00,scattered clouds,310.51,1004,35,10000,6.24

In [38]:
api_key="IBlL4PjmO2G4fxBhz6lbZlohKUPNcerT0kPY9FtB"
request_url=f"https://api.nasa.gov/planetary/apod?api_key={api_key}"
response=requests.get(request_url,params={"count":10})
apod=response.json()
print(json.dumps(apod,indent=5))

[
     {
          "date": "1996-03-02",
          "explanation": "Orbiting 1,075 miles above the Earth, a 250 foot wide, inflated, reinforced nylon \"wheel\" was conceived in the early 1950s to function as a navigational aid, meteorological station, military platform, and way station for space exploration by rocket pioneer Wernher von Braun. The wheel shaped station could be easily rotated creating artificial gravity so that the astronauts would not suffer the effects of prolonged weightlessness. Von Braun and his team favored building a permanently occupied Earth orbiting space station from which to stage a lunar exploration program. But in the 1960s NASA adopted the Apollo Program, which called for astronauts to transfer to a lunar landing vehicle after achieving lunar orbit, bypassing the construction of von Braun's wheel.   Information: The Scale of the Universe Debate in April 1996",
          "hdurl": "https://apod.nasa.gov/apod/image/vonb_wheel.gif",
          "media_type": "image",
          "service_version": "v1",
          "title": "Von Braun's Wheel",
          "url": "https://apod.nasa.gov/apod/image/vonb_wheel.gif"
     },
     {
          "copyright": "CFHT",
          "date": "2021-05-17",
          "explanation": "Is our Milky Way Galaxy this thin?  Magnificent spiral galaxy NGC 4565 is viewed edge-on from planet Earth. Also known as the Needle Galaxy for its narrow profile, bright NGC 4565 is a stop on many telescopic tours of the northern sky, in the faint but well-groomed constellation Coma Berenices. This sharp, colorful image reveals the spiral galaxy's boxy, bulging central core cut by obscuring dust lanes that lace NGC 4565's thin galactic plane. An assortment of other background galaxies is included in the pretty field of view. Thought similar in shape to our own Milky Way Galaxy, NGC 4565 lies about 40 million light-years distant and spans some 100,000 light-years.  Easily spotted with small telescopes, sky enthusiasts consider NGC 4565 to be a prominent celestial masterpiece Messier missed.",
          "hdurl": "https://apod.nasa.gov/apod/image/2105/NGC4565_CFHT_1779.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "NGC 4565: Galaxy on Edge",
          "url": "https://apod.nasa.gov/apod/image/2105/NGC4565_CFHT_960.jpg"
     },
     {
          "date": "1997-06-03",
          "explanation": "If you could look at Venus with radar eyes - this is what you might see. This computer reconstruction of the surface of Venus was created from data from the Magellan spacecraft.  Magellan orbited Venus and used radar to map our neighboring planet's surface between 1990 and 1994. Magellan found many interesting surface features, including the large circular domes, typically 25-kilometers across, that are depicted above. Volcanism is thought to have created the domes, although the precise mechanism remains unknown. Venus' surface is so hot and hostile that no surface probe has lasted more than a few minutes.",
          "hdurl": "https://apod.nasa.gov/apod/image/9706/venus3_mag_big.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "Venus' Once Molten Surface\nCredit:",
          "url": "https://apod.nasa.gov/apod/image/9706/venus3_mag.jpg"
     },
     {
          "date": "2004-10-26",
          "explanation": "What are these surface features on Titan?  This planet-sized moon of Saturn had much of its south polar surface imaged during an initial flyby by the Saturn-orbiting Cassini spacecraft back in early July.  The above image mosaic was digitally stitched together from pictures taken at a very specific color of polarized infrared light, a color not absorbed and little scattered by Titan's methane haze.  Visible are light and dark regions that are not yet understood.  Surface features as small as 10 kilometers are resolved from about 340,000 kilometers away.  The white region near Titan's South Pole, left of center, is unusually thick clouds also thought to be composed of methane.  Today Cassini will swoop to within 1,500 kilometers above Titan and may return data and images that help humanity better understand this strange world.",
          "hdurl": "https://apod.nasa.gov/apod/image/0410/titan1_cassini_big.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "Titan Through the Haze",
          "url": "https://apod.nasa.gov/apod/image/0410/titan1_cassini.jpg"
     },
     {
          "date": "2022-05-01",
          "explanation": "What does a black hole look like? To find out, radio telescopes from around the Earth coordinated observations of black holes with the largest known event horizons on the sky.  Alone, black holes are just black, but these monster attractors are known to be surrounded by glowing gas.  This first image resolves the area around the black hole at the center of galaxy M87 on a scale below that expected for its event horizon.  Pictured, the dark central region is not the event horizon, but rather the black hole's shadow -- the central region of emitting gas darkened by the central black hole's gravity. The size and shape of the shadow is determined by bright gas near the event horizon, by strong gravitational lensing deflections, and by the black hole's spin.  In resolving this black hole's shadow, the Event Horizon Telescope (EHT) bolstered evidence that Einstein's gravity works even in extreme regions, and gave clear evidence that M87 has a central spinning black hole of about 6 billion solar masses.  Since releasing this featured image in 2019, the EHT has expanded to include more telescopes, observe more black holes, track polarized light,and is working to observe the immediately vicinity of the black hole in the center of our Milky Way Galaxy.    This week is: Black Hole Week  New EHT Results to be Announced: Next Thursday",
          "hdurl": "https://apod.nasa.gov/apod/image/2205/M87bh_EHT_2629.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "First Horizon-Scale Image of a Black Hole",
          "url": "https://apod.nasa.gov/apod/image/2205/M87bh_EHT_960.jpg"
     },
     {
          "copyright": "Ken Crawford",
          "date": "2014-03-14",
          "explanation": "NGC 2685 is a confirmed polar ring galaxy - a rare type of galaxy with stars, gas and dust orbiting in rings perpendicular to the plane of a flat galactic disk. The bizarre configuration could be caused by the chance capture of material from another galaxy by a disk galaxy, with the captured debris strung out in a rotating ring. Still, observed properties of NGC 2685 suggest that the rotating ring structure is remarkably old and stable. In this sharp view of the peculiar system also known as Arp 336 or the Helix galaxy, the strange, perpendicular rings are easy to trace as they pass in front of the galactic disk, along with other disturbed outer structures. NGC 2685 is about 50,000 light-years across and 40 million light-years away in the constellation Ursa Major.",
          "hdurl": "https://apod.nasa.gov/apod/image/1403/NGC2685crawford2048.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "Polar Ring Galaxy NGC 2685",
          "url": "https://apod.nasa.gov/apod/image/1403/NGC2685crawford950.jpg"
     },
     {
          "copyright": "Fabian Neyer",
          "date": "2017-10-21",
          "explanation": "Beverly Lynds Dark Nebula 183 lies a mere 325 light-years away, drifting high above the plane of our Milky Way Galaxy. Obscuring the starlight behind it when viewed at optical wavelengths, the dark, dusty molecular cloud itself seems starless. But far infrared explorations reveal dense clumps within, likely stars in the early stages of formation as enhanced regions of the cloud undergo gravitational collapse. One of the closest molecular clouds, it is seen toward the constellation Serpens Caput. This sharp cosmic cloud portrait spans about half a degree on the sky. That's about 3 light-years at the estimated distance of Lynds Dark Nebula 183.",
          "hdurl": "https://apod.nasa.gov/apod/image/1710/ldn183neyer_l1.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "Lynds Dark Nebula 183",
          "url": "https://apod.nasa.gov/apod/image/1710/ldn183neyer_1024.jpg"
     },
     {
          "copyright": "Anthony Ayiomamitis",
          "date": "2011-03-20",
          "explanation": "Did you see the Full Moon last night? Near the horizon, the lunar orb may have seemed to loom large, swollen in appearance by the famous Moon illusion. But the Full Moon really was a large Full Moon last night, reaching its exact full phase within an hour of lunar perigee, the point in the Moon's elliptical orbit closest to planet Earth. A similar near perigee Full Moon last occurred on December 12, 2008. The difference in the Moon's apparent size as it moves from perigee to apogee, its farthest point from Earth, is about 14 percent. Of course, a nearly Full Moon will rise again tonight, lighting the skies on the date of the Equinox or equal night. The Full Moon also looms large in this well-planned, telescopic lunar portrait. Captured earlier this year, the rising lunar orb is dramatically matched to the 2,500 year old Parthenon in Athens, Greece.",
          "hdurl": "https://apod.nasa.gov/apod/image/1103/LunarParthenon_ayiomamitis.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "Parthenon Moon",
          "url": "https://apod.nasa.gov/apod/image/1103/LunarParthenon_ayiomamitis.jpg"
     },
     {
          "date": "1997-04-20",
          "explanation": "On November 17, 1970 the Soviet Luna 17 spacecraft landed the first roving remote-controlled robot on the Moon. Known as Lunokhod 1, it weighed just under 2,000 pounds and was designed to operate for 90 days guided by a 5-person team at the Deep Space Center near Moscow, USSR, Planet Earth. Lunokhod 1 actually toured the lunar Mare Imbrium (Sea of Rains) for 11 months in one of the greatest successes of the Soviet lunar exploration program. The futuristic looking eight wheeler is pictured here in an artist's conception atop its landing module. Ramps extend from both sides of the spacecraft allowing an alternative route to the surface if one side is blocked by boulders.",
          "hdurl": "https://apod.nasa.gov/apod/image/lunokhod_1_big.gif",
          "media_type": "image",
          "service_version": "v1",
          "title": "Moon Robot: Lunokhod 1\r\nCredit:",
          "url": "https://apod.nasa.gov/apod/image/lunokhod_1.gif"
     },
     {
          "copyright": "Yuugi Kitahara",
          "date": "2000-03-01",
          "explanation": "M13 is one of the most prominent and best known globular clusters.  Visible with binoculars in the constellation of Hercules, M13 is frequently one of the first objects found by curious sky gazers seeking celestials wonders beyond normal human vision.   M13 is a colossal home to over 100,000 stars, spans over 150 light years across, lies over 20,000 light years distant, and is over 12 billion years old.  At the 1974 dedication of Arecibo Observatory, a radio message about Earth was sent in the direction of M13.  The reason for the low abundance of unusual blue straggler stars in M13 is currently unknown.",
          "hdurl": "https://apod.nasa.gov/apod/image/0003/m13_kitahara_big.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "M13: The Great Globular Cluster in Hercules",
          "url": "https://apod.nasa.gov/apod/image/0003/m13_kitahara.jpg"
     }
]

In [40]:
url=[]
date=[]
for i in apod:
    url.append(i["url"])
    date.append(i["date"])
df=pd.DataFrame({"URL":url,"Date":date})

In [41]:
df

                                                 URL        Date
0    https://apod.nasa.gov/apod/image/vonb_wheel.gif  1996-03-02
1  https://apod.nasa.gov/apod/image/2105/NGC4565_...  2021-05-17
2  https://apod.nasa.gov/apod/image/9706/venus3_m...  1997-06-03
3  https://apod.nasa.gov/apod/image/0410/titan1_c...  2004-10-26
4  https://apod.nasa.gov/apod/image/2205/M87bh_EH...  2022-05-01
5  https://apod.nasa.gov/apod/image/1403/NGC2685c...  2014-03-14
6  https://apod.nasa.gov/apod/image/1710/ldn183ne...  2017-10-21
7  https://apod.nasa.gov/apod/image/1103/LunarPar...  2011-03-20
8    https://apod.nasa.gov/apod/image/lunokhod_1.gif  1997-04-20
9  https://apod.nasa.gov/apod/image/0003/m13_kita...  2000-03-01